kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: functional-test
spec:
  params:
    - name: SNAPSHOT
      type: string
  tasks:
    - name: functional
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
        steps:
          - name: parse-image
            image: quay.io/konflux-ci/yq:latest
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              #!/bin/bash
              echo "${SNAPSHOT}" | yq -r '.components[].containerImage' | tee $(step.results.image.path)
            results:
              - name: image
                type: string
          - name: test
            image: $(steps.parse-image.results.image)
            script: |
              #!/bin/bash
              /usr/local/bin/e2e-test
